# Auto-generated SVD dimension labels
# edited by nidhi to remove garbage wrods
labels = [
    ["park", "beautiful", "city", "history", "see", "one", "century", "tour", "view", "building", "town", "museum", "island"],
    ["park", "national", "species", "lake", "forest", "mountain", "bird", "island", "wildlife", "animal", "nature", "hike", "trail", "natural", "landscape", "plant", "waterfall", "reserve", "endangered", "cave"],
    ["island", "town", "city", "century", "em", "specie", "historic", "church", "old", "centre", "urban", "de", "colonial", "forest", "sea", "example", "bird", "16th", "street", "marine"],
    ["church", "cathedral", "castle", "monastery", "gothic", "beautiful", "inside", "st", "national", "garden", "architecture", "fresco", "abbey", "stunning", "interior", "romanesque", "tower"],
    ["island", "cave", "tour", "museum", "marine", "rock", "guide", "beach", "sea", "reef", "ocean", "boat", "coral", "archipelago", "fossil"],
    ["castle", "tour", "town", "palace", "city", "garden", "museum", "mine", "fort", "historic", "room", "english", "park", "guide", "walk", "ruin", "interesting", "mining", "roman", "shop"],
    ["island", "temple", "castle", "palace", "garden", "cathedral", "view", "marine", "sea", "fort", "architecture", "beautiful", "beach", "bird", "visit", "fortress", "explore", "ocean", "perfect"],
    ["castle", "monastery", "mountain", "church", "landscape", "lake", "temple", "view", "village", "valley", "mount", "peak", "town", "top", "hill", "region", "wall", "painting", "wooden"],
    ["garden", "palace", "royal", "monastery", "landscape", "building", "fountain", "house", "villa", "room", "cultural", "residence", "design", "traditional", "plant", "tree"],
    ["cave", "cathedral", "castle", "rock", "palace", "gothic", "art", "landscape", "garden", "human", "cultural", "stained", "glass", "painting", "mountain", "architecture", "france", "tower"],
    ["castle", "tomb", "palace", "church", "monastery", "royal", "ruin", "archaeological", "mosque", "ancient", "empire", "painting", "burial"],
    ["cave", "park", "town", "temple", "national", "island", "historic", "old", "monastery", "colonial", "church", "street", "buddhist", "building", "wildlife", "centre", "century", "painting", "architecture", "urban"],
    ["temple", "mine", "tour", "castle", "mining", "cathedral", "guide", "museum", "house", "park", "wildlife", "building", "english", "industrial", "specie", "guided", "nbsp", "forest", "national"],
    ["park", "island", "roman", "cave", "ruin", "view", "hike", "church", "parking", "walk", "da", "city", "trail", "lake", "get", "top", "wall", "stato", "mosaic"],
    ["monastery", "mosque", "tour", "em", "mine", "cave", "tomb", "mountain", "century", "city", "mining", "bus", "guide", "ticket", "orthodox", "cathedral", "de", "monastic", "founded", "monk"],
    ["lake", "temple", "park", "palace", "mine", "island", "cave", "cathedral", "roman", "mining", "tour", "castle", "national", "century", "underground", "archaeological", "landscape", "english", "royal", "glacier"],
    ["cave", "species", "forest", "garden", "city", "palace", "bird", "reserve", "mosaic", "endangered", "ruin", "villa", "reef", "basilica", "threatened", "plant", "sea", "tropical"],
    [ "mosque", "fort", "cave", "church", "islamic", "boat", "mine", "shah", "nbsp", "architectural", "water", "world", "architecture", "bird", "glacier", "iran", "dome", "isfahan", "ottoman"],


    
    ["lake", "monastery", "fossil", "bird", "rock", "museum", "temple", "animal", "specie", "reserve", "historic", "centre", "art", "old", "em", "city", "street", "town", "garden", "see"],
    ["tomb", "mosque", "church", "dynasty", "bus", "old", "burial", "shrine", "china", "thracian", "walk", "town", "islamic", "necropolis", "lot", "nice", "city", "wooden", "chinese", "japan"],
    ["fort", "lake", "tomb", "fossil", "palace", "museum", "san", "fortification", "spanish", "fortress", "temple", "de", "royal", "view", "military", "caribbean", "wall", "king", "rohtas", "history"],
    ["tomb", "de", "water", "lake", "san", "la", "bird", "boat", "bridge", "santiago", "mine", "monument", "castle", "river", "compostela", "heritage", "burial", "world", "route", "thracian"],
    ["de", "mosque", "san", "fossil", "la", "mountain", "university", "islamic", "mission", "garden", "castle", "spanish", "jesuit", "santa", "volcano", "museum", "mount", "16th", "ticket", "church"],
    ["rock", "mine", "palace", "tour", "guide", "mining", "lake", "em", "carving", "city", "church", "mountain", "town", "hike", "experience", "forest", "art", "mount", "history", "painting"],
    ["rock", "temple", "monastery", "mine", "fossil", "garden", "fort", "bridge", "park", "reef", "water", "marine", "town", "old", "mining", "sea", "mosque", "beach", "coral", "carving"],
    ["palace", "village", "ruin", "guide", "cathedral", "river", "road", "church", "tour", "water", "valley", "city", "boat", "people", "system", "traditional", "mosque", "desert", "landscape", "san"],
    ["fossil", "palace", "bridge", "whale", "span", "million", "valley", "history", "evolution", "reef", "museum", "marine", "cliff", "river", "de", "wine", "beach", "year", "world", "earth"],
    ["bridge", "city", "river", "span", "canal", "china", "sup", "boat", "art", "museum", "aqueduct", "chinese", "industrial", "rock", "railway", "grotto", "engineering", "ride", "university", "island"],
    ["city", "garden", "fossil", "university", "tour", "reef", "water", "ruin", "marine", "cathedral", "system", "abbey", "world", "guide", "fountain", "church", "ancient", "coral", "cliff", "centre"],
    ["village", "tour", "roman", "fossil", "building", "dynasty", "wall", "tower", "guide", "china", "mosaic", "traditional", "chinese", "architecture", "guided", "basilica", "preserved", "fortress", "grotto", "house"],
    ["reef", "marine", "coral", "museum", "shark", "glacier", "lagoon", "turtle", "system", "art", "fish", "atoll", "palace", "barrier", "building", "habitat", "water", "dugong", "rock", "specie"],
    ["abbey", "tour", "guide", "span", "town", "bridge", "forest", "temple", "guided", "wine", "university", "english", "rock", "glacier", "city", "sup", "old", "landscape", "royal", "german"],
    ["wine", "city", "de", "museum", "abbey", "vineyard", "fort", "bird", "mine", "university", "tasting", "view", "santiago", "great", "landscape", "compostela", "mountain", "temple", "vine", "route"],
    ["city", "desert", "monastery", "mine", "house", "wall", "street", "museum", "forest", "fortress", "like", "temple", "inside", "glacier", "human", "planning", "underground", "mining", "one", "yazd"],
    ["village", "bus", "rock", "san", "forest", "ruin", "city", "park", "specie", "lake", "ticket", "span", "house", "museum", "bridge", "railway", "preserved", "traditional", "mission", "station"],
    ["town", "de", "ruin", "bus", "grotto", "buddhist", "china", "abbey", "old", "chinese", "route", "buddha", "longmen", "dynasty", "fort", "park", "santiago", "sup", "entrance", "ancient"],
    ["sup", "span", "th", "nbsp", "great", "wine", "fortress", "university", "building", "city", "view", "tasting", "good", "ancient", "lake", "industrial", "rock", "champagne", "shrine", "best"],
    ["span", "university", "reef", "mountain", "bus", "village", "basilica", "marine", "monument", "sup", "shrine", "mount", "coral", "world", "route", "century", "th", "japan", "garden", "villa"],
    ["abbey", "basilica", "fort", "san", "art", "fresco", "mountain", "mosaic", "castle", "desert", "st", "valley", "painting", "night", "wine", "day", "span", "early", "system", "water"],
    ["wine", "forest", "historic", "basilica", "mosaic", "landscape", "cultural", "villa", "river", "shrine", "colonial", "get", "fossil", "vineyard", "entrance", "centre", "sacred", "bus", "parking", "tasting"],
    ["bridge", "spanish", "mountain", "guide", "tour", "reef", "garden", "ruin", "mount", "river", "span", "wine", "old", "tomb", "fort", "mosque", "coral", "valley", "ottoman", "nice"],
    ["abbey", "san", "mosque", "spanish", "colonial", "mountain", "boat", "university", "bird", "fortress", "shrine", "mission", "mount", "jesuit", "wall", "sea", "top", "well", "walk", "information"],
    ["glacier", "university", "capital", "empire", "roman", "fortress", "royal", "river", "rock", "shrine", "spanish", "beautiful", "east", "history", "ice", "restaurant", "bridge", "building", "km", "west"],
    ["canal", "forest", "aqueduct", "water", "system", "old", "see", "centre", "site", "monument", "trail", "roman", "mosaic", "tour", "santiago", "hydraulic", "villa", "human", "fort", "compostela"],
    ["san", "tower", "desert", "abbey", "valley", "nbsp", "mission", "wall", "wine", "old", "jesuit", "span", "pyramid", "landscape", "specie", "statue", "grotto", "plant", "volcano", "national"],
    ["san", "sea", "town", "university", "mission", "landscape", "day", "jesuit", "system", "nature", "waterfall", "ticket", "museum", "water", "glacier", "ice", "mill", "train", "japan", "line"],
    ["glacier", "span", "ice", "sup", "historic", "spanish", "china", "greenland", "temple", "roman", "sea", "th", "garden", "mosque", "centre", "tomb", "museum", "village", "nbsp", "chinese"],
    ["fortress", "bus", "sup", "colonial", "garden", "empire", "wall", "villa", "archaeological", "san", "experience", "reef", "gorilla", "town", "atlantic", "citadel", "fresco", "spanish", "back", "th"],
    ["university", "valley", "glacier", "fort", "villa", "wine", "village", "mine", "campus", "road", "bridge", "view", "canal", "mosaic", "world", "art", "mexico", "new", "parking", "aqueduct"],
    ["valley", "route", "basilica", "museum", "garden", "rock", "river", "mill", "bird", "mosaic", "colonial", "santiago", "tour", "heritage", "compostela", "industrial", "kremlin", "kathmandu", "pilgrimage", "sup"],
    ["china", "archaeological", "de", "early", "kremlin", "tour", "well", "day", "mill", "remains", "red", "bridge", "painting", "view", "period", "reserve", "chinese", "da", "square", "basilica"],
    ["glacier", "tower", "villa", "bridge", "gorilla", "buddhist", "railway", "volcano", "medina", "de", "mosaic", "city", "fortified", "12th", "western", "exceptional", "japan", "forest", "buddha", "shop"],
    ["sup", "empire", "san", "bus", "mission", "hall", "bird", "capital", "aqueduct", "archaeological", "water", "city", "town", "specie", "house", "bear", "centre", "mine", "th", "achaemenid"],
    ["tower", "university", "roman", "station", "train", "bell", "capital", "railway", "free", "well", "staff", "urban", "church", "river", "valley", "archaeological", "india", "system", "village", "medina"],
    ["valley", "mound", "centre", "view", "tour", "europe", "000", "historic", "road", "atlantic", "dolmen", "forest", "preserved", "building", "sea", "nice", "buddhist", "fortress", "beautiful", "human"],
    ["glacier", "city", "wine", "pyramid", "mountain", "industrial", "garden", "coal", "mound", "stone", "000", "africa", "animal", "people", "inside", "da", "monument", "square", "worker", "town"],
    ["wine", "specie", "world", "volcano", "colonial", "sea", "canal", "spanish", "heritage", "human", "archaeological", "railway", "tasting", "ticket", "vineyard", "japan", "train", "outstanding", "early", "example"],
    ["pyramid", "mountain", "bird", "route", "mexico", "tower", "new", "waterfall", "built", "university", "architecture", "inside", "fresco", "abbey", "people", "sup", "north", "region", "plant", "fall"],
    ["ruin", "fresco", "painting", "wall", "al", "fortress", "gorilla", "valley", "da", "kremlin", "historic", "canal", "forest", "chapel", "fossil", "experience", "tomb", "kazan", "russian", "shrine"],
    ["glacier", "basilica", "tower", "route", "christian", "road", "burial", "valley", "stone", "work", "trail", "st", "underground", "art", "central", "chapel", "mine", "fresco", "mission", "mound"],
    ["house", "villa", "mining", "hike", "km", "mission", "coal", "day", "great", "sea", "trail", "good", "grotto", "hunting", "archaeological", "wall", "region", "room", "recommended", "camp"],
    ["bus", "monument", "wall", "bird", "stone", "medina", "glacier", "fossil", "group", "landscape", "cultural", "road", "aqueduct", "villa", "horse", "age", "number", "light", "painting", "late"],
    ["boat", "tower", "basilica", "ruin", "abbey", "sup", "wine", "year", "railway", "hike", "mosaic", "river", "building", "world", "small", "000", "brick", "largest", "mine", "asia"],
    ["house", "royal", "gorilla", "basilica", "monument", "system", "see", "hill", "valley", "ruin", "carving", "archaeological", "mountain", "13th", "fortress", "terrace", "view", "island", "agricultural", "14th"],
    ["basilica", "centre", "railway", "fortress", "plant", "train", "center", "visitor", "good", "mosaic", "mound", "industrial", "well", "walk", "old", "landscape", "route", "ancient", "east", "hill"],
    ["villa", "route", "africa", "history", "tomb", "south", "architectural", "square", "modern", "system", "east", "europe", "mission", "need", "trade", "west", "tower", "le", "water", "compostela"],
    ["nbsp", "beautiful", "tour", "canal", "university", "view", "mission", "example", "fortress", "worth", "historic", "iran", "art", "two", "aqueduct", "outstanding", "site", "wooden", "property", "railway"],
    ["sup", "railway", "forest", "tiger", "landscape", "hike", "painting", "santiago", "english", "reef", "valley", "statue", "sundarbans", "incredible", "new", "day", "atlantic", "compostela", "mangrove", "worth"],
    ["canal", "baroque", "nbsp", "east", "room", "history", "rsquo", "mount", "south", "australia", "north", "medina", "long", "network", "art", "around", "cultural", "top", "square", "citadel"],
    ["canal", "span", "shrine", "tower", "dynasty", "st", "road", "planning", "basilica", "south", "experience", "ice", "medina", "history", "bridge", "since", "rideau", "architecture", "phoenician", "da"],
    ["shrine", "gorilla", "boat", "art", "railway", "archaeological", "great", "painting", "reserve", "hall", "experience", "inca", "road", "square", "rainforest", "fresco", "sacred", "islamic", "mound", "tide"],
    ["gorilla", "villa", "baroque", "mill", "building", "experience", "side", "ancient", "human", "old", "university", "forest", "sri", "al", "inside", "glacier", "santiago", "silk", "factory", "ticket"],
    ["nbsp", "villa", "gorilla", "mission", "village", "fortress", "valley", "guide", "university", "jesuit", "hall", "entrance", "carving", "rsquo", "atlantic", "information", "coast", "dynasty", "saint", "boat"],
    ["gorilla", "desert", "portuguese", "st", "mound", "industrial", "renaissance", "specie", "amazing", "hall", "view", "empire", "stone", "carving", "coal", "gothic", "ruin", "kremlin", "life", "fossil"],
    ["reserve", "buddhist", "desert", "fortress", "house", "bridge", "inside", "settlement", "building", "entrance", "capital", "water", "wine", "industrial", "underground", "natural", "mayan", "age", "century", "network"],
]
